name: Watershed Mapping Pipeline

on:
  pull_request:
    branches: [ main, master ]

env:
  # Set headless mode for GIS applications
  QT_QPA_PLATFORM: offscreen
  MPLBACKEND: Agg

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Free up disk space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        df -h
        
    - name: Install Nix
      uses: cachix/install-nix-action@v23
      with:
        nix_path: nixpkgs=channel:nixos-unstable
        
    - name: Setup Nix cache
      uses: cachix/cachix-action@v12
      with:
        name: nixpkgs-unfree
        skipPush: true
        
    - name: Make scripts executable
      run: |
        chmod +x scripts/*.sh
        
    - name: Create required directories
      run: |
        mkdir -p data/{raw,processed} output grassdb
        
    - name: Test Nix environment
      run: |
        nix-shell shell.nix --run "echo 'Testing basic commands...'"
        nix-shell shell.nix --run "which python3 || echo 'Python3 not found'"
        nix-shell shell.nix --run "which grass || echo 'GRASS not found'"
        
    - name: Run complete pipeline
      run: |
        cd scripts
        nix-shell ../shell.nix --run "./complete_pipeline.sh"
      continue-on-error: true
        
    - name: Check outputs
      run: |
        echo "=== Output directory contents ==="
        ls -la output/ || echo "No output directory"
        echo "=== Data processed directory contents ==="
        ls -la data/processed/ || echo "No processed data directory"
        echo "=== Pipeline logs ==="
        find . -name "*.log" -exec cat {} \; || echo "No log files found"
        
    - name: Upload pipeline outputs
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: watershed-mapping-outputs
        path: |
          output/
          data/processed/
          *.log
        retention-days: 7